name: Hosting...

on:
  workflow_dispatch:
    inputs:
      DUMP_URL:
        description: 'Dump URL'
        required: true
      DUMP_FILE_NAME:
        description: "Dump's file name"
        required: true


jobs:
  Host:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "DUMP URL: ${{ github.event.inputs.DUMP_URL }}"
        echo "Starting Command: ${{ github.event.inputs.STARTING_COMMAND }}"
        echo "DUMP FILE NAME: ${{ github.event.inputs.DUMP_FILE_NAME }}"
        echo "::endgroup::"
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Install dependencies
      run: |
        curl -S https://raw.githubusercontent.com/DumprX/DumprX/main/setup.sh > setup.sh && bash setup.sh
        sudo apt install -y aria2;


    - name: Download & Dump Device
      run: |
        git clone https://github.com/DumprX/DumprX && cd DumprX && aria2c ${{ github.event.inputs.DUMP_URL }} && ./dumper.sh ${{ github.event.inputs.DUMP_FILE_NAME }} 

      
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

        - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          DumprX/${{ github.event.inputs.DUMP_FILE_NAME }}/*
        name: Dump .-.
        tag_name: ${{ github.run_id }}
        body: |
          ``${{ github.event.inputs.DUMP_URL }}``
          DUMP_FILE_NAME: [${{ github.event.inputs.DUMP_FILE_NAME }}]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
      